services:
  # リバースプロキシ
  nginx:
    # イメージ
    image: nginx:latest

    # ポート
    ports:  
      - "8633:8443"

    tty: true

    # ディレクトリ共有
    volumes:
      # 設定ファイル
      - ./nginx/configs:/etc/nginx/conf.d/

      # 静的ファイル
      - ./nginx/statics:/var/www/nginx/statics/:ro

      # SSL証明書
      - ./nginx/keys:/etc/nginx/ssl:ro

      # ロギングディレクトリ
      - ./nginx/logs:/var/log/nginx:rw

    # 自動再起動
    restart: always
    depends_on:
      - frontend
      - app
  # フロントエンドのコンテナ
  frontend:
    # ホスト名設定
    hostname: frontend

    # イメージ
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development-dependencies-env

    # ディレクトリ共有
    volumes:
      - ./frontend:/app

    restart: always

  # app コンテナ
  app:
    # ホスト名指定
    hostname: app

    # ビルド対象のdockerfileをしてい
    build:
      context: ./app
      dockerfile: dockerfile
      target: Develop
    env_file:
      - ./config/app.env
    
    # コードを共有
    volumes:
      - ./app/src:/app/src
    
    # 仮想端末を有効化
    tty: true

    # 自動起動を有効化
    restart: always

  mysql-db:
    hostname: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: meecha
      MYSQL_PASSWORD: meecha_pass
      MYSQL_DATABASE: meecha
      TZ: Asia/Tokyo
    volumes:
      - ./database/db-data:/var/lib/mysql

  mysql-test:
    hostname: mysql-db-test
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: meecha
      MYSQL_PASSWORD: meecha_pass
      MYSQL_DATABASE: meecha
      TZ: Asia/Tokyo
